In [257]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# scaling and train test split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

#one hot encoding
from sklearn.preprocessing import OneHotEncoder

# evaluation on test data
from sklearn.metrics import mean_squared_error,mean_absolute_error,explained_variance_score
from sklearn.metrics import classification_report,confusion_matrix

In [258]:
file_path = "\\Users\\eggfr\\Flatiron\\Flatiron_phase2_project\\dsc-phase-2-project\\data\\kc_house_data.csv"
project2_raw_df = pd.read_csv(file_path)

In [259]:
project2_raw_df.head()

id        date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  10/13/2014  221900.0         3       1.00         1180   
1  6414100192   12/9/2014  538000.0         3       2.25         2570   
2  5631500400   2/25/2015  180000.0         2       1.00          770   
3  2487200875   12/9/2014  604000.0         4       3.00         1960   
4  1954400510   2/18/2015  510000.0         3       2.00         1680   

   sqft_lot  floors waterfront  view  ...          grade sqft_above  \
0      5650     1.0        NaN  NONE  ...      7 Average       1180   
1      7242     2.0         NO  NONE  ...      7 Average       2170   
2     10000     1.0         NO  NONE  ...  6 Low Average        770   
3      5000     1.0         NO  NONE  ...      7 Average       1050   
4      8080     1.0         NO  NONE  ...         8 Good       1680   

   sqft_basement yr_built  yr_renovated  zipcode      lat     long  \
0            0.0     1955           0.0    98178  47.5112 -122.257   
1          400.0     1951        1991.0    98125  47.7210 -122.319   
2            0.0     1933           NaN    98028  47.7379 -122.233   
3          910.0     1965           0.0    98136  47.5208 -122.393   
4            0.0     1987           0.0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [260]:
y = project2_raw_df['price']
X= project2_raw_df.drop('price',1)

C:\Users\eggfr\AppData\Local\Temp\ipykernel_19280\2342642404.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X= project2_raw_df.drop('price',1)


In [261]:
#create train-test set using 75-25 (train-test and random state = 42) randomly split the data
x_train, x_test, y_train, y_test = train_test_split(X, y ,test_size=0.25,random_state=42)
# shape of train and test splits
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16197, 20), (5400, 20), (16197,), (5400,))

In [262]:
project2_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21597 non-null  int64  
 1   date           21597 non-null  object 
 2   price          21597 non-null  float64
 3   bedrooms       21597 non-null  int64  
 4   bathrooms      21597 non-null  float64
 5   sqft_living    21597 non-null  int64  
 6   sqft_lot       21597 non-null  int64  
 7   floors         21597 non-null  float64
 8   waterfront     19221 non-null  object 
 9   view           21534 non-null  object 
 10  condition      21597 non-null  object 
 11  grade          21597 non-null  object 
 12  sqft_above     21597 non-null  int64  
 13  sqft_basement  21597 non-null  object 
 14  yr_built       21597 non-null  int64  
 15  yr_renovated   17755 non-null  float64
 16  zipcode        21597 non-null  int64  
 17  lat            21597 non-null  float64
 18  long  

In [263]:
project2_raw_df.isnull().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [264]:
project2_raw_df.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.159700e+04  2.159700e+04  21597.000000  21597.000000  21597.000000   
mean   4.580474e+09  5.402966e+05      3.373200      2.115826   2080.321850   
std    2.876736e+09  3.673681e+05      0.926299      0.768984    918.106125   
min    1.000102e+06  7.800000e+04      1.000000      0.500000    370.000000   
25%    2.123049e+09  3.220000e+05      3.000000      1.750000   1430.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    sqft_above      yr_built  yr_renovated  \
count  2.159700e+04  21597.000000  21597.000000  21597.000000  17755.000000   
mean   1.509941e+04      1.494096   1788.596842   1970.999676     83.636778   
std    4.141264e+04      0.539683    827.759761     29.375234    399.946414   
min    5.200000e+02      1.000000    370.000000   1900.000000      0.000000   
25%    5.040000e+03      1.000000   1190.000000   1951.000000      0.000000   
50%    7.618000e+03      1.500000   1560.000000   1975.000000      0.000000   
75%    1.068500e+04      2.000000   2210.000000   1997.000000      0.000000   
max    1.651359e+06      3.500000   9410.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21597.000000  21597.000000  21597.000000   21597.000000   21597.000000  
mean   98077.951845     47.560093   -122.213982    1986.620318   12758.283512  
std       53.513072      0.138552      0.140724     685.230472   27274.441950  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471100   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.231000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [265]:
x_train['date'] = pd.to_datetime(x_train['date'])
x_train['month'] = x_train['date'].apply(lambda date:date.month)
x_train['year'] = x_train['date'].apply(lambda date:date.year)
x_train = x_train.drop('date',axis=1)

x_test['date'] = pd.to_datetime(x_test['date'])
x_test['month'] = x_test['date'].apply(lambda date:date.month)
x_test['year'] = x_test['date'].apply(lambda date:date.year)
x_test = x_test.drop('date',axis=1)

#x_test['date'] = pd.to_datetime(x_test['date'])
#x_test['month'] = x_test['date'].apply(lambda date:date.month)
#x_test['year'] = x_test['date'].apply(lambda date:date.year)
#x_test = x_test.drop('date',axis=1)
# Check the new columns
print(x_train.columns.values)

['id' 'bedrooms' 'bathrooms' 'sqft_living' 'sqft_lot' 'floors'
 'waterfront' 'view' 'condition' 'grade' 'sqft_above' 'sqft_basement'
 'yr_built' 'yr_renovated' 'zipcode' 'lat' 'long' 'sqft_living15'
 'sqft_lot15' 'month' 'year']


In [266]:
project2_raw_df['sqft_basement'].unique()

array(['0.0', '400.0', '910.0', '1530.0', '?', '730.0', '1700.0', '300.0',
       '970.0', '760.0', '720.0', '700.0', '820.0', '780.0', '790.0',
       '330.0', '1620.0', '360.0', '588.0', '1510.0', '410.0', '990.0',
       '600.0', '560.0', '550.0', '1000.0', '1600.0', '500.0', '1040.0',
       '880.0', '1010.0', '240.0', '265.0', '290.0', '800.0', '540.0',
       '710.0', '840.0', '380.0', '770.0', '480.0', '570.0', '1490.0',
       '620.0', '1250.0', '1270.0', '120.0', '650.0', '180.0', '1130.0',
       '450.0', '1640.0', '1460.0', '1020.0', '1030.0', '750.0', '640.0',
       '1070.0', '490.0', '1310.0', '630.0', '2000.0', '390.0', '430.0',
       '850.0', '210.0', '1430.0', '1950.0', '440.0', '220.0', '1160.0',
       '860.0', '580.0', '2060.0', '1820.0', '1180.0', '200.0', '1150.0',
       '1200.0', '680.0', '530.0', '1450.0', '1170.0', '1080.0', '960.0',
       '280.0', '870.0', '1100.0', '460.0', '1400.0', '660.0', '1220.0',
       '900.0', '420.0', '1580.0', '1380.0', '475.0', 

In [267]:
# change the inproper datatype for 'sqft_basement'
x_train['sqft_basement'] = x_train['sqft_basement'].apply(lambda x: float(x.replace("?", "297")))
x_train['sqft_basement'] = x_train['sqft_basement'].apply(lambda x: float(x))
#x_train['sqft_basement'].dtype
x_test['sqft_basement'] = x_test['sqft_basement'].apply(lambda x: float(x.replace("?", "297")))
x_test['sqft_basement'] = x_test['sqft_basement'].apply(lambda x: float(x))



In [268]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5400 entries, 3686 to 2358
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             5400 non-null   int64  
 1   bedrooms       5400 non-null   int64  
 2   bathrooms      5400 non-null   float64
 3   sqft_living    5400 non-null   int64  
 4   sqft_lot       5400 non-null   int64  
 5   floors         5400 non-null   float64
 6   waterfront     4780 non-null   object 
 7   view           5386 non-null   object 
 8   condition      5400 non-null   object 
 9   grade          5400 non-null   object 
 10  sqft_above     5400 non-null   int64  
 11  sqft_basement  5400 non-null   float64
 12  yr_built       5400 non-null   int64  
 13  yr_renovated   4437 non-null   float64
 14  zipcode        5400 non-null   int64  
 15  lat            5400 non-null   float64
 16  long           5400 non-null   float64
 17  sqft_living15  5400 non-null   int64  
 18  sqft_

In [269]:
project2_raw_df['floors'].value_counts()

1.0    10673
2.0     8235
1.5     1910
3.0      611
2.5      161
3.5        7
Name: floors, dtype: int64

In [270]:
project2_raw_df['waterfront'].value_counts()

NO     19075
YES      146
Name: waterfront, dtype: int64

In [271]:
#fill na with no value and change yes to 1 n no to 0 #since majority of the sales has no waterfront.
x_train['waterfront'] = x_train['waterfront'].fillna(value = 'NO')
x_train['waterfront'] = x_train['waterfront'].replace(to_replace = ['YES','NO'],value = [1,0])
x_train['waterfront'].value_counts()


0    16086
1      111
Name: waterfront, dtype: int64

In [272]:
x_test['waterfront'] = x_test['waterfront'].fillna(value = 'NO')
x_test['waterfront'] = x_test['waterfront'].replace(to_replace = ['YES','NO'],value = [1,0])
x_test.value_counts()
x_test['waterfront'].value_counts()

0    5365
1      35
Name: waterfront, dtype: int64

In [273]:
project2_raw_df['view'].value_counts()
#data1 = x_train["view"].reshape(-1,1)
#encoder = OneHotEncoder(sparse=False)
#onehot = encoder.fit_transform(data1)

NONE         19422
AVERAGE        957
GOOD           508
FAIR           330
EXCELLENT      317
Name: view, dtype: int64

In [274]:
# fill na with no value -->majority is none and could be N/A as none as well. 
x_train['view'] = x_train['view'].fillna(value = 'NONE')
x_test['view'] = x_test['view'].fillna(value = 'NONE')

In [275]:
x_test['view'].unique()

array(['NONE', 'FAIR', 'AVERAGE', 'GOOD', 'EXCELLENT'], dtype=object)

In [276]:
print(len(x_train['view']))

16197


In [277]:
x_train[['view']]

view
6405   NONE
937    NONE
19076  NONE
15201  NONE
13083  NONE
...     ...
11964  NONE
21575  NONE
5390   NONE
860    NONE
15795  NONE

[16197 rows x 1 columns]

In [299]:
ohe = OneHotEncoder(drop='first')
data =  x_train[['view']]
view_df = pd.DataFrame(ohe.fit_transform(data).toarray(), index = x_train.index)
view_df.columns = ['view_0','view_1','view_2','view_3']
view_df.shape
concatenated_df = pd.concat([x_train,view_df],axis=1)

In [300]:
x_train.tail()

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
11964  7853230570         3       2.50         2230      5800     2.0   
21575  4140940150         4       2.75         2770      3852     2.0   
5390   8658300480         4       1.50         1530      9000     1.0   
860    1723049033         1       0.75          380     15000     1.0   
15795  8567450080         4       2.50         2755     11612     2.0   

       waterfront  view condition          grade  ...  sqft_basement  \
11964           0  NONE   Average      7 Average  ...            0.0   
21575           0  NONE   Average         8 Good  ...            0.0   
5390            0  NONE      Good  6 Low Average  ...            0.0   
860             0  NONE   Average         5 Fair  ...            0.0   
15795           0  NONE   Average         8 Good  ...            0.0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
11964      2004           0.0    98065  47.5308 -121.847           2230   
21575      2014           NaN    98178  47.5001 -122.232           1810   
5390       1976           0.0    98014  47.6492 -121.908           1520   
860        1963           0.0    98168  47.4810 -122.323           1170   
15795      2001           0.0    98019  47.7394 -121.965           2820   

       sqft_lot15  month  year  
11964        6088      9  2014  
21575        5641     10  2014  
5390         8500      7  2014  
860         15000      6  2014  
15795       12831      3  2015  

[5 rows x 21 columns]

In [301]:
view_df.tail()

view_0  view_1  view_2  view_3
11964     0.0     0.0     0.0     1.0
21575     0.0     0.0     0.0     1.0
5390      0.0     0.0     0.0     1.0
860       0.0     0.0     0.0     1.0
15795     0.0     0.0     0.0     1.0

In [302]:
concatenated_df = pd.concat([x_train,view_df],axis=1)
concatenated_df.tail()

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
11964  7853230570         3       2.50         2230      5800     2.0   
21575  4140940150         4       2.75         2770      3852     2.0   
5390   8658300480         4       1.50         1530      9000     1.0   
860    1723049033         1       0.75          380     15000     1.0   
15795  8567450080         4       2.50         2755     11612     2.0   

       waterfront  view condition          grade  ...      lat     long  \
11964           0  NONE   Average      7 Average  ...  47.5308 -121.847   
21575           0  NONE   Average         8 Good  ...  47.5001 -122.232   
5390            0  NONE      Good  6 Low Average  ...  47.6492 -121.908   
860             0  NONE   Average         5 Fair  ...  47.4810 -122.323   
15795           0  NONE   Average         8 Good  ...  47.7394 -121.965   

       sqft_living15  sqft_lot15  month  year  view_0  view_1  view_2  view_3  
11964           2230        6088      9  2014     0.0     0.0     0.0     1.0  
21575           1810        5641     10  2014     0.0     0.0     0.0     1.0  
5390            1520        8500      7  2014     0.0     0.0     0.0     1.0  
860             1170       15000      6  2014     0.0     0.0     0.0     1.0  
15795           2820       12831      3  2015     0.0     0.0     0.0     1.0  

[5 rows x 25 columns]

In [282]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = x_train['view']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['NONE' 'NONE' 'NONE' ... 'NONE' 'NONE' 'NONE']
[4 4 4 ... 4 4 4]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
['NONE']
